### ISSUE TITLE
Patches for DDK22.3 are not working with Bianbu tag v2.0.4

### ISSUE THREAD

**Issue by cwt** [Icenowy/aosc-os-pvr#1]
Patches for DDK22.3 are not working with the new Bianbu tag [v2.0.4](https://gitee.com/bianbu-linux/mesa3d/tree/v2.0.4).

**Comment by Icenowy** [comment]
It's no longer 22.3, but 24.2 instead.

**Comment by cwt** [comment]
@Icenowy Where I can find DDK24.2? Is it (or just the patches) available yet?

**Comment by Icenowy** [comment]
I need some more investigation currently. Please wait for a few days (I am working on some other architectures recently).

**Comment by cwt** [comment]
@Icenowy Don't worry, no rush. The old Mesa wrapper built with DDK 22.3 is somehow still working with the new v2.0.4 kernel and GPU firmware.

**Comment by Icenowy** [comment]
Yes, I think the libpvr_dri_support.so has some kind of ABI stability.

**Comment by Icenowy** [comment]
untested commits pushed (for being fetched by the build system).

**Comment by Icenowy** [comment]
Tested now -- it proves that xf86-video-pvrdri needs bump to suite DDK 24.2 .

**Comment by cwt** [comment]
Built and package for Arch is working. Thanks!
